### ISSUE TITLE
How to support different destination currencies?

### ISSUE THREAD

**Issue by aboodman** [tythe-protocol/tythe#3]
Maintainers are going to be all over the world. I'm not sure how it should work to get them paid in their native currency. Perhaps that's a property of the `type` in `tythe.json`.

**Comment by benwerd** [comment]
I also wonder what happens if this is incompatible with an organization's abilities. eg:

* the only listed `type` is `dogecoin` but the organization has no way to pay in dogecoin
* the library lists wire details for a country that their bank does not support sending funds to

Or when there are security issues with payment details. eg if banking details could be used for payment in the author's home country (this is true in the UK with Direct Debits - you just need an account and routing number to sign up for payments).

The solution to both sets of problems may be to allow a tight initial set of payment options chosen for their abstracted addresses.

**Comment by aboodman** [comment]
I split this concept out into a [separate repository](https://github.com/aboodman/dot-donate). I think you're right that it is important to just have a few payment types that are very general. Right now I'm going with USDC, BTC, and PayPal.
